#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} - {{ .Folder }}'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = '◤'
    foreground = '#e0ab38'
    background = '#1c2226'
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    leading_diamond = '🮋'
    trailing_diamond = '◤'
    foreground = '140'
    # background = '#1c2226'
    background = '235'
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}}  <b><i>{{ .UserName }}</i></b> '

    [blocks.segments.properties]
      arch = ''
      debian = ''
      fedora = ''
      linux = ''
      macos = ''
      manjaro = ''
      opensuse = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    # leading_diamond = ''
    trailing_diamond = '◤'
    foreground = 'cyan'
    background = '240'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = '…'
      folder_separator_icon = '/'
      home_icon = '~'
      max_depth = 2.0
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    trailing_diamond = '◤'
    foreground = 'lightBlue'
    background = '238'
    template = ' {{ .HEAD }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 20.0
      truncate_symbol = '…'
      fetch_stash_count = true
      fetch_status = true
      branch_icon = ' '


  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#65a7d6'
    foreground_templates = ['{{ if gt .Code 0 }}#ba4206{{ end }}']
    background = '#1c2226'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{.Code}}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'blue'
    template = '$'

[transient_prompt]
  foreground = 'blue'
  template = '$ '

[secondary_prompt] 
  background = 'transparent'
  foreground = 'blue'
  template = '| '
