
import = ["~/.config/alacritty/rose-pine.toml"]
shell = "zsh"
live_config_reload = true

[window]
padding = { x = 3 }
decorations = "None"
opacity = 0.8

[font]
normal = { family = "SpaceMono Nerd Font Mono", style = "Regular" }
size = 11
